# fly.toml app configuration file generated for node-express-starter-2022 on 2023-11-17T15:45:55Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "node-express-starter-2022"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
